# Generated by Django 4.2.17 on 2025-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avl_app', '0002_pathpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='timestamp',
            new_name='last_updated',
        ),
        migrations.AlterField(
            model_name='location',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pathpoint',
            name='device_id',
            field=models.CharField(max_length=255),
        ),
    ]
